### ISSUE TITLE
Using an internal link to reference a page results in undefined link

### ISSUE THREAD

**Issue by Bratalix** [NewFrontDoor/pwad.org.au#65]
Unsure if that is intended or not, liturgy references work fine.

**Comment by BarryThePenguin** [comment]
I did notice that.. been playing around with pwad in my spare time and noticed one of the links was `undefined`.. I'll push my changes soon, and we can take a look at what's causing the issue.

I have a feeling the issue is in the query to sanity 👀

**Comment by Bratalix** [comment]
Could be right, I only noticed when I was troubleshooting the undefined link for them. Didn't actually take a look at the sanity query but likely to be the culprit as you say.

**Comment by Bratalix** [comment]
Fixed in #70
